name: sahayak_hello
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
    
  # UI
  cupertino_icons: ^1.0.8
  
  # Firebase packages
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.12
  firebase_auth: ^5.7.0
  firebase_ai: ^2.3.0
  
  # Google Cloud dependencies
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  
  # Voice integration
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.3
  permission_handler: ^12.0.1
  
  # Storage and utilities
  http: ^1.2.1
  hive: ^2.2.3
  path_provider: ^2.1.2
  
  # File handling and date formatting
  firebase_storage: ^12.0.4
  file_picker: ^8.0.0+1
  image_picker: ^1.0.7
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# ✅ SINGLE FLUTTER SECTION WITH ASSETS
flutter:
  uses-material-design: true
  
  # Assets for Google Cloud service account
  assets:
    - assets/google_service_account.json
